# Hyperparameter search space for experiments

learning_rate:
  values: [1.0e-3, 5.0e-4, 1.0e-4, 5.0e-5]

dropout:
  values: [0.2, 0.3, 0.4, 0.5]

gcn_layers:
  values: [2, 3, 4]

num_clusters:
  values: [500, 1000, 1500, 2000]

superpixel_segments:
  values: [1000, 1500, 2000]